# Generated by Django 5.0.6 on 2024-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
