# Generated by Django 5.0.6 on 2024-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
