# Generated by Django 5.0.6 on 2024-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
